version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
      - '5555:5555' # Prisma Studioのポート
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules # ホスト側のnode_modulesをコンテナにマウント
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chatdb

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  # コンテナを再起動してもデータ消えなくなるらしいので入れました
