version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    working_dir: /backend
    ports:
      - '3000:3000'
      - '5555:5555' # Prisma Studioのポート
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/chatdb

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    working_dir: /frontend
    ports:
      - '3001:3000'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  # コンテナを再起動してもデータ消えなくなるらしいので入れました
