FROM ubuntu:22.04

WORKDIR /backend

ENV LANG=ja_JP.UTF-8
ENV TZ=Asia/Tokyo

RUN apt-get update && \
    apt-get install -y locales curl procps && \
    locale-gen ja_JP.UTF-8 && \
    localedef -f UTF-8 -i ja_JP ja_JP

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs

# PrismaCLIのためにOpenSSLをインストール
# Procpsはクラッシュ対策
RUN apt-get update && apt-get install -y openssl procps && rm -rf /var/lib/apt/lists/*

# Dockerイメージ内でpnpmを使用するためにCorepackを有効化
RUN corepack enable && corepack prepare pnpm@10.13.1 --activate

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --force


COPY . .

EXPOSE 3000

CMD ["pnpm", "start:dev"]
